// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestesFOILMinimalApi.Data;

#nullable disable

namespace TestesFOILMinimalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250828130543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestesFOILMinimalApi.Models.CategoriaPerguntaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("ValeUm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("categorias_perguntas", (string)null);
                });

            modelBuilder.Entity("TestesFOILMinimalApi.Models.PerguntaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoriaPerguntaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_pergunta_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPerguntaId");

                    b.ToTable("pergunta", (string)null);
                });

            modelBuilder.Entity("TestesFOILMinimalApi.Models.PerguntaModel", b =>
                {
                    b.HasOne("TestesFOILMinimalApi.Models.CategoriaPerguntaModel", "CategoriaPergunta")
                        .WithMany("Perguntas")
                        .HasForeignKey("CategoriaPerguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPergunta");
                });

            modelBuilder.Entity("TestesFOILMinimalApi.Models.CategoriaPerguntaModel", b =>
                {
                    b.Navigation("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
